version: '3.7'

services:

  app:
    container_name: datawow_test_server
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3001:3001"
    volumes:
      - ./config.yaml:/app/config.yaml
